### ISSUE TITLE
Error during execution of generateKotlinGrammarSource on gradle 8.13

### ISSUE THREAD

**Issue by knz-ru** [Strumenta/antlr-kotlin#223]
After upgrading to Gradle 8.13 we are getting an error:

```
* What went wrong:
Execution failed for task ':api:generateKotlinGrammarSource'.
> Process 'Gradle ANTLR Kotlin Worker 4' finished with non-zero exit value 1
```

This seems to be the cause, although it's not colored as error in build logs:
```
java.lang.NoSuchMethodError: net/rubygrapefruit/platform/Native.init(Ljava/io/File;)Lnet/rubygrapefruit/platform/Native; (loaded from file:/<...>/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-daemon-client/1.9.23/e0b07c4ac39283a657444955faec3d0e0f1bd3aa/kotlin-daemon-client-1.9.23.jar by java.net.URLClassLoader@6a225c96) called from class org.gradle.internal.nativeintegration.services.NativeServices (loaded from file:/<...>/.gradle/wrapper/dists/gradle-8.13-bin/5xuhj0ry160q40clulazy9h7d/gradle-8.13/lib/gradle-native-8.13.jar by java.net.URLClassLoader@6a225c96).
	at org.gradle.internal.nativeintegration.services.NativeServices.<init>(NativeServices.java:281)
	at org.gradle.internal.nativeintegration.services.NativeServices.initialize(NativeServices.java:260)
	at org.gradle.internal.nativeintegration.services.NativeServices.initializeOnWorker(NativeServices.java:240)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:99)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```

Everything is working fine on Gradle versions 8.8-8.12.

**Comment by lppedd** [comment]
Never seen this one tbh. I guess we'd need a small reproducer if possible.

**Comment by lppedd** [comment]
@ftomassetti can close this one if you want.

**Comment by ftomassetti** [comment]
Thank you @lppedd . Closing
